// <auto-generated />
namespace VIPP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CountDays : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CountDays));
        
        string IMigrationMetadata.Id
        {
            get { return "202010211943251_CountDays"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
